#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v4
# autospec commit: e738c511eb94
#
Name     : pam-python
Version  : 20333b56dce49495ea14d39c0937a137a652c418
Release  : 3
URL      : https://github.com/sunweaver/pam-python/archive/20333b56dce49495ea14d39c0937a137a652c418/pam-python-20333b56dce49495ea14d39c0937a137a652c418.tar.gz
Source0  : https://github.com/sunweaver/pam-python/archive/20333b56dce49495ea14d39c0937a137a652c418/pam-python-20333b56dce49495ea14d39c0937a137a652c418.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : AGPL-3.0
Requires: pam-python-lib = %{version}-%{release}
Requires: pam-python-license = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : pypi-sphinx
BuildRequires : python3-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Set-our-security-dir.patch
Patch2: backport-use-new-PyConfig-API-when-building-against-Python-3.12-and-beyond.patch

%description
pam_python
==========
pam_python is a PAM module that runs the Python interpreter
and so allows PAM modules to be written in Python.

%package doc
Summary: doc components for the pam-python package.
Group: Documentation

%description doc
doc components for the pam-python package.


%package lib
Summary: lib components for the pam-python package.
Group: Libraries
Requires: pam-python-license = %{version}-%{release}

%description lib
lib components for the pam-python package.


%package license
Summary: license components for the pam-python package.
Group: Default

%description license
license components for the pam-python package.


%prep
%setup -q -n pam-python-20333b56dce49495ea14d39c0937a137a652c418
cd %{_builddir}/pam-python-20333b56dce49495ea14d39c0937a137a652c418
%patch -P 1 -p1
%patch -P 2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709057868
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1709057868
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pam-python
cp %{_builddir}/pam-python-%{version}/debian/copyright %{buildroot}/usr/share/package-licenses/pam-python/f61bb69fe63e01305f9e7b67b689aa0e3d887256 || :
export GOAMD64=v2
GOAMD64=v2
%make_install LIBDIR=/usr/lib64/security

%files
%defattr(-,root,root,-)

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/pam_python/examples/pam_deny.py
/usr/share/doc/pam_python/examples/pam_nologin.py
/usr/share/doc/pam_python/examples/pam_permit.py
/usr/share/doc/pam_python/html/_sources/pam_python.rst.txt
/usr/share/doc/pam_python/html/_static/alabaster.css
/usr/share/doc/pam_python/html/_static/basic.css
/usr/share/doc/pam_python/html/_static/custom.css
/usr/share/doc/pam_python/html/_static/doctools.js
/usr/share/doc/pam_python/html/_static/documentation_options.js
/usr/share/doc/pam_python/html/_static/file.png
/usr/share/doc/pam_python/html/_static/language_data.js
/usr/share/doc/pam_python/html/_static/minus.png
/usr/share/doc/pam_python/html/_static/plus.png
/usr/share/doc/pam_python/html/_static/pygments.css
/usr/share/doc/pam_python/html/_static/searchtools.js
/usr/share/doc/pam_python/html/_static/sphinx_highlight.js
/usr/share/doc/pam_python/html/genindex.html
/usr/share/doc/pam_python/html/index.html
/usr/share/doc/pam_python/html/objects.inv
/usr/share/doc/pam_python/html/pam_python.html
/usr/share/doc/pam_python/html/search.html
/usr/share/doc/pam_python/html/searchindex.js

%files lib
%defattr(-,root,root,-)
/usr/lib64/security/pam_python.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pam-python/f61bb69fe63e01305f9e7b67b689aa0e3d887256
